name: CI/CD to DockerHub & EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ---------------- CHECKOUT REPO ----------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------- LOGIN TO DOCKER HUB ----------------
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------------- BUILD & PUSH DOCKER IMAGE ----------------
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: kishangollamudi/onlinebookstore:latest

      # ---------------- DEPLOY TO EC2 ----------------
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            sudo docker pull kishangollamudi/onlinebookstore:latest

            echo "Stopping old container..."
            sudo docker stop bookstore-app || true

            echo "Removing old container..."
            sudo docker rm bookstore-app || true

            echo "Running new container..."
            sudo docker run -d \
              -p 8080:8080 \
              --name bookstore-app \
              kishangollamudi/onlinebookstore:latest

            echo "Deployment complete!"
